const width = 5;
const height = 10;
const area = width * height;
console.log('the value of area: ', area);
console.log('typeof area: ', typeof area);
const bill = 50;
const payment = 100;
const change = payment - bill;
console.log('the value of change: ', change);
console.log('typeof change: ', typeof change);
const quizzes = 100;
const midterm = 99;
const final = 100;
const grade = (quizzes + midterm + final) / 3;
console.log('the value of grade: ', grade);
console.log('the typeof grade: ', typeof grade);
const firstName = 'Walter';
const lastName = 'White';
let fullName = firstName + ' ' + lastName;
console.log('the value of fullName: ', fullName);
console.log('the typeof fullName: ', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('the value of isAcidic: ', isAcidic);
console.log('the typeof of isAcidic: ', typeof isAcidic);
const headCount = 9000;
const isSparta = headCount === 300;
console.log('value of isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
const motto = fullName += ' is the GOAT';
console.log('value of motto: ', motto);
console.log('typeof motto: ', typeof motto);
